### ISSUE TITLE
PEM routines:OPENSSL_internal:NO_START_LINE

### ISSUE THREAD

**Issue by mvergaz** [guiqui/k8Studio#11]
I receive this log output:
`Error Loading cluster error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE`
when I've configured Cluster Authentication = Certificate.
The file which contents I've introduced are:
.minikube/ca.crt
.minikube/profiles/minikube/client.crt
.minikube/profiles/minikube/client.key

**Comment by guiqui** [comment]
Can you tell me what operating system are you using?

**Comment by mo-othman** [comment]
Hi @mvergaz  
Thanks for reporting the issue   

we are introducing a new option to add the paths instead of opening the files and copying them 
I have tested it with Minikube and it’s working perfectly, we are going to release a new version today later with the fix

**Comment by mo-othman** [comment]
Hi @mvergaz We have released 0.1.2-alpha and now you use certificate authority, client-certificate and client-key as an option

let me know if the problem is solved

Thanks!

**Comment by guiqui** [comment]
Fix in 0.1.2-alpha
