### ISSUE TITLE
does not allow access to any cluster

### ISSUE THREAD

**Issue by beniju** [guiqui/k8Studio#12]
---------
App Version 0.1.2-alpha
Arch: x64
Platform: win32
osRelease: 10.0.22621
Locale: en-US
---------
Hello, I am trying to test your product, but in all the Clusters that I have configured, I have the same error, it seems that it tries to render the cluster data and then gives the error.

![image](https://github.com/guiqui/k8Studio/assets/16580176/22d32661-593a-482b-89c5-fc9606893d09)

**Comment by beniju** [comment]
Actually I do have the config file, in .kube/config.
Should I add the path to the file somewhere?
The strange thing is that it seems that this file is being accessed, because all my Clusters appear in the main panel

![image](https://github.com/guiqui/k8Studio/assets/16580176/e20e907f-c392-408d-a02f-3ef3941b395e)


Thank you!

**Comment by mo-othman** [comment]
Hi @beniju, We have reproduced the issue you have, It's a typo in our end, we are fixing it right now and we will do a new release (0.1.3-alpha) with the fix.

**Comment by beniju** [comment]
Hello @mo-othman thanks! 
I'll be waiting for the release to try it.

**Comment by mo-othman** [comment]
Hello @beniju, we have released 0.1.3-alpha which contains the fix

**Comment by beniju** [comment]
awesome, works, @mo-othman thank you so much!

**Comment by elibrody** [comment]
Having this same issue on windows
