### ISSUE TITLE
source code is missing

### ISSUE THREAD

**Issue by zrks** [guiqui/k8Studio#20]
unfortunately I don't see any source code and/or reference to it

**Comment by mo-othman** [comment]
You can download the app through releases or from the download page on our website  https://k8studio.io/download/

**Comment by mo-othman** [comment]
Currently, our project is not open source, and we haven’t made the source code publicly available
We appreciate your understanding in this matter. If there are questions or information you need about the project, I'd be more than happy to help where I can."

**Comment by alvsanand** [comment]
I don't see a point to create a public repo in GitHub with no code. It gives a false impression of openness...

**Comment by prochac** [comment]
> I don't see a point to create a public repo in GitHub with no code. It gives a false impression of openness...

The GitHub serves as a reporting platform for free testing labour. The project is IMO not meant to be open sourced.

**Comment by tpcgold** [comment]
Good thing I found this issue before loading k8Studio 👍 . There is no way I would ever use a non-open-source tool in my K8s environment
