### ISSUE TITLE
MacOS(arm) download link is 404

### ISSUE THREAD

**Issue by EigoOda** [guiqui/k8Studio#22]
link address: https://github.com/guiqui/k8Studio/releases/download/v0.2.0-alpha/K8Studio-0.2.0-alpha-arm64.dmg
<img width="1570" alt="image" src="https://github.com/guiqui/k8Studio/assets/56793934/de00da3c-d8e1-4a56-874c-0c063a4ade43">

**Comment by mo-othman** [comment]
Hi @EigoOda, Thanks for reporting the issue, we have updated the website.

**Comment by EigoOda** [comment]
@mo-othman 
Thanks!
