### ISSUE TITLE
Add option to skip sign in for airtight environments

### ISSUE THREAD

**Issue by guidorugo** [guiqui/k8Studio#25]
As the title says, allow a way to skip sign in for airtight environment AKA environments without internet access.

**Comment by guiqui** [comment]
Absolutely, @guidorugo, your observation is spot on. We currently have a partially completed solution in progress. Our plan is to finalize the implementation and include it in our upcoming release. Thank you for bringing this to our attention!

**Comment by mo-othman** [comment]
Hi @guidorugo, we're excited to announce the release of [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)!

In this update, we've completely revamped of the authentication workflow,  now offering support for airtight environments.

For a more in-depth overview, please refer to the release notes. 
Thanks!
