### ISSUE TITLE
Setting: mouse zoom reverse

### ISSUE THREAD

**Issue by chevdor** [guiqui/k8Studio#26]
That's probably already on your radar but if not, here is an issue for it :)

The UI looks already very nice. How zomming works is really a matter of personal preference and having the zoom direction "reversed" (compared to the user's expectation) kinda ruines the initial experience.

Is there a way to provide a config or an ENV to reverse the zoom direction ?

**Comment by mo-othman** [comment]
Hi @chevdor I have double checked the zooming, Can I know which OS you are using? I could reproduced it on Windows machine
It's gonna be fixed soon

**Comment by jkrusy** [comment]
I can reproduce that on a Mac. Have to scroll "down" to zoom in

**Comment by chevdor** [comment]
I am on a Mac and usually, the zooming/scrolling is opposite to what is done on Windows, but that can also be controlled by the user via settings.

Not judging what makes sense or not but if only one opinionated zoom direction is supported, it will make one or the other half of the users unhappy about the zoom direction :)

I need to scroll up to zoom in whereas my expectation (Figma for instance, and most other software actually) is the opposite.

**Comment by chevdor** [comment]
I just tested the 0.2.3-alpha and it works now as expected, thank you !
