### ISSUE TITLE
Not working on Azure Kubernetes cluster

### ISSUE THREAD

**Issue by anumalasri** [guiqui/k8Studio#29]
---------
App Version 0.2.2-alpha
Arch: x64
Platform: darwin
osRelease: 22.6.0
Locale: en-US
---------

Unable to view resources on Azure Cluster.  Both Deployment and Grip views are empty 

<img width="930" alt="image" src="https://github.com/guiqui/k8Studio/assets/27963315/1c88fbe9-11af-441a-af88-f4eed570795a">

**Comment by mo-othman** [comment]
Hi @anumalasri, Thanks for reporting the issue
Can you provide us your cluster Kubernetes version?

**Comment by anumalasri** [comment]
Azure cluster with Kubernetes version: **1.27.7**

**Comment by mo-othman** [comment]
Hi @anumalasri we have release 0.2.3-alpha
Do you still have the issue?
