### ISSUE TITLE
Did not receive activation email

### ISSUE THREAD

**Issue by MarkCupitt** [guiqui/k8Studio#31]
Tried two different email addresses, unable to log in

**Comment by MarkCupitt** [comment]
markcupitt@billrush.co.nz if you want to manually activate it

**Comment by paunis** [comment]
Same issue. Activation mail not coming.

**Comment by mo-othman** [comment]
Hi @MarkCupitt @paunis Thanks for reporting the issue.
we have fixed the issue.

let me know if you still can't login

**Comment by paunis** [comment]
Still not receiving any mail

**Comment by mo-othman** [comment]
Hi @paunis we have updated it, let me if still has an issue

**Comment by hb12devtn** [comment]
Hi @mo-othman, same here, I signed up 30 minutes ago and didn't receive the activation code.

**Comment by sbhosle-tibco** [comment]
Same issue, I too didn't receive the activation code

**Comment by anothersmith** [comment]
+1 no email received either

**Comment by sbhosle-tibco** [comment]
Update: Team manually activated my account. I'm in!

**Comment by mo-othman** [comment]
We have sent emails to everyone, let me know if you still have an issue to login.
we are moving to use SES to avoid this issue again

**Comment by fcjack** [comment]
I tried to sign up, but did not receive the email with the activation code.

**Comment by fcjack** [comment]
Ok, I received today, probably was only slow to send the email, all good now

**Comment by mo-othman** [comment]
Thanks!
