### ISSUE TITLE
Demo Video isn't available on YouTube

### ISSUE THREAD

**Issue by senlakshman** [guiqui/k8Studio#32]
The demo video url is not available in YouTube,

o watch a demo take a look at [video](https://youtu.be/tYMUfhlKFgU) 
![image](https://github.com/guiqui/k8Studio/assets/7485185/0d6dfb3f-d853-4a6e-be41-840d63491ba7)

**Comment by mo-othman** [comment]
Hi @senlakshman Thanks for reporting the issue, we have updated the readme 

here's the youtube channel link
https://www.youtube.com/channel/UC84bcmR2JVP8MBeLEjXxHIA
