### ISSUE TITLE
Please add how to configure the K8S to read the cluster 

### ISSUE THREAD

**Issue by senlakshman** [guiqui/k8Studio#33]
It would be great, if you can add how to configure K8S to configure and read the supports clusters.

**Comment by mo-othman** [comment]
Hi @senlakshman We will be adding the documentation soon. meanwhile you can press on add cluster or add the kubeconfig path through the settings icon

**Comment by kolonuk** [comment]
How do you use a kubeconfig file? I can't see an import or open option in the "Add Cluster" screen.

**Comment by mo-othman** [comment]
@kolonuk You can add the path through here
<img width="508" alt="Screenshot 2024-01-18 191034" src="https://github.com/guiqui/k8Studio/assets/42744048/67b1c2e5-6cc2-44f6-8b94-9a7674ef257e">
