### ISSUE TITLE
New K8s Cluster Creation Not Working 

### ISSUE THREAD

**Issue by NMSVishal** [guiqui/k8Studio#36]
---------
App Version 0.2.2-alpha
Arch: x64
Platform: win32
osRelease: 10.0.22621
Locale: en-US
---------

Not able to create new k8s cluster , submit button is not available on cluster creation page

**Comment by mo-othman** [comment]
Hi @NMSVishal Can you share which submit button you mean? we don't create clusters
or you mean when adding a cluster?
