### ISSUE TITLE
Scroll wheel direction

### ISSUE THREAD

**Issue by kolonuk** [guiqui/k8Studio#40]
It certainly feels that the scroll wheel zoom is reversed.

For example, Google maps, "up" is zoom in, where as in k8studio, it is zoom out.  It's a little confusing depending on where you come from I suppose.

**Comment by kolonuk** [comment]
Also, can the zoom be quicker, with accelleration perhaps?

**Comment by mo-othman** [comment]
Hi @kolonuk Thanks for pointing this out! Can I know which OS you are using? I have reproduced the reverse zooming on windows so this is a bug

For a quicker zoom We will do it and maybe will make it configurable. 
Will be great to know if you are using a normal mouse, magic mouse or touchpad

**Comment by kolonuk** [comment]
Apologies, I'm using Windows with a normal cheap Logitech mouse - M310.

**Comment by klubi** [comment]
On MacOS if you pinch on trackpad (bring fingers closer) the preview gets bigger, while by default in MacOS this gesture should make things smaller.

**Comment by mo-othman** [comment]
We have fixed this issue in the new release 0.2.3

Looking forward to hearing your feedbacks!

**Comment by mo-othman** [comment]
Fixed in release 0.2.3-alpha
