### ISSUE TITLE
Log button opens command prompt

### ISSUE THREAD

**Issue by kolonuk** [guiqui/k8Studio#41]
I've selected a pod, and clicked the Log button, and instead of showing the logs, it opens a command prompt.

**Comment by mo-othman** [comment]
Hi @kolonuk thanks for reporting the issue, I have reproduced it, the fix will be in the next release

**Comment by kolonuk** [comment]
Thanks! I know it's only Alpha, but still it's a really good start! Especially the RBAC manager - thats something over and above Lens!

**Comment by mo-othman** [comment]
Thanks John! we are happy that you are enjoying it! we have good features in our pipelines
let us know if there's any interesting feature you are looking for!

**Comment by mo-othman** [comment]
Fixed in release 0.2.3-alpha
