### ISSUE TITLE
Unable to resize columns on "Permissions" window

### ISSUE THREAD

**Issue by kolonuk** [guiqui/k8Studio#42]
When clicking on the separator, all I can do is drag the column to the left. I have a long namespace and resource names.

Also, unable to drag the popup window.

**Comment by mo-othman** [comment]
Hi @kolonuk, The grid issue of resizing the columns is fixed in release 0.2.3-alpha
For dragging the window, i agree it should be draggable. It will be done soon

**Comment by mo-othman** [comment]
Hi @jkrusy , we're excited to announce the release of [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)!

In this update, Modals now are draggable 

Thanks!

**Comment by mo-othman** [comment]
Hi @kolonuk , we're excited to announce the release of [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)!

In this update, Modals now are draggable

Thanks!
