### ISSUE TITLE
Cannot validate account

### ISSUE THREAD

**Issue by dragon74** [guiqui/k8Studio#44]
I registered with mail and password. Got a verification code but it was declared invalid :(
Later no more codes were sent.
---------
App Version 0.2.2-alpha
Arch: x64
Platform: win32
osRelease: 10.0.22621
Locale: en-US
---------

**Comment by mo-othman** [comment]
Hi @dragon74 Can you try again and let me know if you can't login?

**Comment by mo-othman** [comment]
Hi @MR-Os1 There was an issue with the email service, we have sent emails let me know if you have a trouble logging in

**Comment by MR-Os1** [comment]
it's fine now but I can't test it because I'm just verified now, and I can't get code.
