### ISSUE TITLE
Difficulties login in after signing up.

### ISSUE THREAD

**Issue by samueldison** [guiqui/k8Studio#45]
---------
App Version 0.2.2-alpha
Arch: x64
Platform: win32
osRelease: 10.0.19045
Locale: en-US
---------
Followed the sign up procedures but cant login using email address nor password.

**Comment by mo-othman** [comment]
Hi @samueldison Have you tried to reset password? Can you share with us the email you have used if you don't mind? you can also PM us on slack or email it to info@k8studio.io if you don't want to post it here

**Comment by samueldison** [comment]
Hi,

Yes I tried to change the password. However it wasn't possible.

Email : ***@***.***

**Comment by mo-othman** [comment]
Btw the email is masked it shows  ***@***.***

**Comment by samueldison** [comment]
I'm not sure I understand you.
However, I signed up using a new email.
Haven't received the confirmation code yet.

**Comment by samueldison** [comment]
Hi, still haven't received the confirmation code.

**Comment by mo-othman** [comment]
Hi @samueldison Sorry, There was an issue going on with email service, can you try to login again?

**Comment by Orion83-h** [comment]
Still can't login.
I'd created a new account using a new email but I still haven't received the confirmation code.
I'm sure I can't go any further without a confirmation code with the new email address.

**Comment by mo-othman** [comment]
Hi @Orion83-h can you share the email address? because earlier when you shared it, it was masked like *****@**.**

**Comment by Orion83-h** [comment]
samuelhaddison71@gmail.com

**Comment by mo-othman** [comment]
Just to confirm if this is the same email was used while signing up because we can't find the account

**Comment by Orion83-h** [comment]
I'd used a new email address to create a new account but didn't receive a confirmation code. That's the reason why you can't find the account.
This is the initial email address that was masked... samuelhaddison71@gmail.com.

**Comment by mo-othman** [comment]
Sorry , Can you share the new email you have used?

**Comment by Orion83-h** [comment]
***@***.***

**Comment by Orion83-h** [comment]
orionhouse83@gmail.com.

**Comment by samueldison** [comment]
orionhouse83@gmail.com

**Comment by mo-othman** [comment]
We have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta), we have redesigned that part
