### ISSUE TITLE
cant get logs

### ISSUE THREAD

**Issue by alperen-selcuk** [guiqui/k8Studio#47]
tried multiple times but cant get logs "No Rows to show" when i try command line with kubectl logs i can get logs. 

---------
App Version 0.2.2-alpha
Arch: arm64
Platform: darwin
osRelease: 22.1.0
Locale: en-US
---------

**Comment by mo-othman** [comment]
To get logs 
- Select an item
- Press the logs icon on toolbar 

<img width="411" alt="logs-icon" src="https://github.com/guiqui/k8Studio/assets/42744048/9a6d950e-a900-45f0-8ad4-4e3f7f44592d">


It's broken right now, we are shipping a new release has a the fix

**Comment by mo-othman** [comment]
Hi @alperen-selcuk We have release 0.2.3 which has the bug fix i mentioned earlier

let me know if it's working for you!

**Comment by mo-othman** [comment]
Fixed in release 0.2.3-alpha
