### ISSUE TITLE
Feature: Allow multiple kubeconfig files

### ISSUE THREAD

**Issue by jkrusy** [guiqui/k8Studio#48]
I am using multiple kubeconfig files for managing my cluster settings. 
It should be possible to allow adding clusters from different kubeconfigs without switching the used kubeconfig in the settings.

**Comment by mo-othman** [comment]
Hi @jkrusy Thanks for pointing this out, we are working on this!

**Comment by mo-othman** [comment]
Hi @jkrusy , we're excited to announce the release of [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)!

In this update, The application supports multi kubeconfig files 

Thanks!
