### ISSUE TITLE
Setting the kubeconfig path does not work

### ISSUE THREAD

**Issue by jkrusy** [guiqui/k8Studio#49]
I tried to change the path to the kubeconfig file and it does not work. The UI still shows the clusters in the default kubeconfig file.
I am also missing a button to save the changes
![image](https://github.com/guiqui/k8Studio/assets/10153696/797421d4-f7ca-4099-a182-d6933508e0c6)

**Comment by jkrusy** [comment]
ah yes. refreshing works. The experience should definitely be improved on this.

**Comment by mo-othman** [comment]
We will soon!

closing this ticket since no issue
