### ISSUE TITLE
Front page is annoying if I have a lot of EKS clusters

### ISSUE THREAD

**Issue by dex4er** [guiqui/k8Studio#50]
Just look at this:

<img width="1508" alt="image" src="https://github.com/guiqui/k8Studio/assets/174367/1a6c7fc1-70c9-4f35-bd6d-3b8dc958b16c">

I'm not even sure what should I click. Settings some aliases or abbreviations for each cluster would be welcomed.

**Comment by chy168** [comment]
encounter the same issue when there are many clusters
![image](https://github.com/guiqui/k8Studio/assets/424758/1a620b7b-90e4-4e17-8171-8bfc8c1394d2)

**Comment by mo-othman** [comment]
Hello @chy168 @dex4er , we're excited to announce the release of [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)!

In this update, , we've completely revamped of the cluster manager page.
We have introduced a new view (table view), grouping, visibility and more features!

We are looking forward to hearing your feedbacks.
Thanks!

**Comment by mo-othman** [comment]
Closed due to inactivity
