### ISSUE TITLE
Connection Lost: Please reload the custer to reconnect

### ISSUE THREAD

**Issue by makten** [guiqui/k8Studio#51]
I'm unable to use the tool. I constantly get Connection Lost with an option to reload. I just installed the tool and have not succeeded once to open my cluster.

**Comment by mo-othman** [comment]
Hi @makten we have found a related bug, we are shipping a new release soon with the fix

**Comment by mo-othman** [comment]
Hi @makten Do you have the same issue using the latest release? v 0.2.3-alpha

**Comment by makten** [comment]
@mo-othman This issue is resolved now after the update. 👍
