### ISSUE TITLE
Filtering on deployment view leaves artifacts

### ISSUE THREAD

**Issue by lmingle** [guiqui/k8Studio#53]
---------
App Version 0.2.2-alpha
Arch: x64
Platform: win32
osRelease: 10.0.19045
Locale: en-US
---------
I selected the Deployment filter and cleared all items except for one. After pressing the 'save changes' button the screen was redrawn but lines connecting previously shown items remain.

![image](https://github.com/guiqui/k8Studio/assets/480797/da8bf3cc-98fe-4c3d-b662-294cd16246fe)

**Comment by mo-othman** [comment]
Hi we have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta), The issue should be fixed
