### ISSUE TITLE
Deployment filter with nothing selected

### ISSUE THREAD

**Issue by lmingle** [guiqui/k8Studio#54]
---------
App Version 0.2.2-alpha
Arch: x64
Platform: win32
osRelease: 10.0.19045
Locale: en-US
---------
On the deployment tab filter, if I deselect the namespaces checkbox and press 'save changes' button I expect everything to be cleared from the view. Instead, all items are displayed.

**Comment by guiqui** [comment]
Thanks @lmingle  I can reproduce it.

**Comment by guiqui** [comment]
This one should be fixed for version next version 0.2.4

**Comment by mo-othman** [comment]
Hi we have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta), The issue should be fixed
