### ISSUE TITLE
K8Studio-Setup-0.2.3-alpha.exe does not work

### ISSUE THREAD

**Issue by lucardcoder** [guiqui/k8Studio#55]
Installed the Windows version to test it, but when I click K8Studio-Setup-0.2.3-alpha.exe nothing happens.

**Comment by mo-othman** [comment]
Hi @lucardcoder I have just tested it and it's working

Can you double check if an anti virus is blocking the installation?

**Comment by lucardcoder** [comment]
> Hi @lucardcoder I have just tested it and it's working
> 
> Can you double check if an anti virus is blocking the installation?

I have disabled my anti-virus but still no installation happens.

**Comment by mo-othman** [comment]
If you don't mind, can you share the os version and arch?

**Comment by lucardcoder** [comment]
> If you don't mind, can you share the os version and arch?

It`s Windows 11 x64

**Comment by mo-othman** [comment]
I'm having the same setup actually 

Is it possible to send me the exe file? i think ZIP is acceptable here if not I can provide an email

**Comment by lucardcoder** [comment]
> I'm having the same setup actually
> 
> Is it possible to send me the exe file? i think ZIP is acceptable here if not I can provide an email

I had to right-click and unblock the application to run the setup. It is working now. Will report any other bugs here.

Thanks for your help!
