### ISSUE TITLE
Error Loading cluster Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by magarciasopo** [guiqui/k8Studio#57]
Unable to connect to the cluster. 

I need to establish proxy environment variables to redircect the traffic. 
These environment variables are: 

NO_PROXY
HTTP_PROXY
HTTPS_PROXY

Otherwise, the logs are: 
[2024-01-20 15:36:01.152] [error] Client network socket disconnected before secure TLS connection was established
[2024-01-20 15:36:01.153] [error] Error Loading cluster Client network socket disconnected before secure TLS connection was established

**Comment by guiqui** [comment]
HI @magarciasopo thanks for reporting! Yes, we missed this one. We are going to start reading the env variable and apply the proxy information to our request to the kube-api.

**Comment by mo-othman** [comment]
Hey @magarciasopo , quick question! I'm curious about how you handle proxy passwords. Do you typically set up your HTTP_PROXY variable directly with the password like HTTP_PROXY=http://user:password@proxy:port/, or do you use a tool like Credential Manager? Just looking for some insights! 😊 so we can test different setups

**Comment by martinfj** [comment]
Hi @mo-othman , same issue as @magarciasopo.
I want to use k8studio into a corporative network so I have to do this in my mac.
 
```
export HTTP_PROXY=x.x.x.x:1234                                                                                                           ✔ │ 4s  │ 12:43:15 
export HTTPS_PROXY=x.x.x.x:1234

```

_launch from terminal in order to get global envs_ 
`open K8Studio.app`
So issues related to _...secure TLS connection.._ were fixed  but I see a new error after inject http proxy setup vars

> ] tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.x.x:80 - Local (x.x.x.x:64760)
> [error] tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.x.x:80 - Local (x.x.x.x:64760)
> [error] Error Loading cluster tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.x.x:80 - Local (x.x.x.x:64760)

Any idea how to proceed..?

Many Thanks, 
P.D. I like your solution and I can't wait for use it 
:)

**Comment by mo-othman** [comment]
Hi @martinfj the current production version doesn't work with proxy

We have been working on this issue and other issues related (inc redesigning some parts of the app) we are in the testing phase before releasing it soon, expected to be released in few days.

I will keep you posted!

**Comment by mo-othman** [comment]
Hello, we're excited to announce the release of [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)!

In this update, the application now supports proxy functionality. You can conveniently add the URL through cluster settings, proxy-url in kubeconfig, or system/terminal environment variables.

For a more in-depth overview, please refer to the release notes.
Thanks!
