### ISSUE TITLE
not able to send email at the time of signup

### ISSUE THREAD

**Issue by rajatshukla058** [guiqui/k8Studio#58]
---------
App Version 0.2.3-alpha
Arch: x64
Platform: linux
osRelease: 5.15.0-91-generic
Locale: en-GB
---------

**Comment by fclaudio-palmeira** [comment]
+1

**Comment by fclaudiopalmeira** [comment]
Also happening to me:

App Version 0.2.3-alpha
Arch: x64
Platform: Windows 11
Locale: en-GB

**Comment by mo-othman** [comment]
Hi @fclaudiopalmeira @rajatshukla058!

My apologizes, we have missed this ticket.

We have migrated our email servers few weeks ago, The issue should be fixed

**Comment by mo-othman** [comment]
We have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta), we have redesigned that part
