### ISSUE TITLE
K8Studio Not accepting Proxy settings

### ISSUE THREAD

**Issue by tusharnath31** [guiqui/k8Studio#59]
I have proxy setup done in terminal, but k8studio is not picking it up, I could not find any option to update proxy configuration on a cluster level as well.

**Comment by mo-othman** [comment]
Hi @tusharnath31 

Are you doing it through environment variables?
NO_PROXY
HTTP_PROXY
HTTPS_PROXY

If yes let's continue here #57

**Comment by mo-othman** [comment]
Hello, we're excited to announce the release of [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)!

In this update, the application now supports proxy functionality. You can conveniently add the URL through cluster settings, proxy-url in kubeconfig, or system/terminal environment variables.

Thanks!
