### ISSUE TITLE
Dosn't integrate with Bitwarden

### ISSUE THREAD

**Issue by Asgoret** [guiqui/k8Studio#60]
Desktop APP needed registration for FREE use and more of that: is doesn't catch up with Bitwarden password application. Disable password for local purpose or add integration to password applications.

**Comment by mo-othman** [comment]
Hello, we're excited to announce the release of [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)!

In this update, we've completely revamped the authentication workflow, allowing you to seamlessly integrate password applications/management tools directly in your browser. Additionally, we've introduced licenses and a guest mode for enhanced flexibility.

For a more in-depth overview, please refer to the release notes.

Thanks!
