### ISSUE TITLE
Automatically disconnects with error illegal base 64 data

### ISSUE THREAD

**Issue by gavinvw** [guiqui/k8Studio#61]
---------
App Version 0.2.3-alpha
Arch: x64
Platform: win32
osRelease: 10.0.19045
Locale: en-US
---------
OS: WSL2 hosted Ubuntu 20.04
OS VERSION="20.04.6 LTS (Focal Fossa)"

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3803

Docker version 24.0.5, build a61e2b4
minikube version: v1.30.1

Summary:
Once specifying the correct configuration files during 'Add Cluster' and connecting k8studio to WSL2 running minikube/docker within the cluster loads successfully but then exists with the below error. Note:  UNC path is used: \\wsl$\Ubuntu\home\user\.minikube 

Expected Behavior:
After loading successfully k8studio would continue to work. 

Actual Behavior 
The below error is received and k8studio returns to the homepage.  Log indicate successful load but no error.

![image](https://github.com/guiqui/k8Studio/assets/4069336/882fecda-05c8-47c0-921b-e157b9af4c72)

**Comment by mo-othman** [comment]
Actually, We are working it atm, the new approach will allow you to add multiply files, we are trying to include it in the next release

**Comment by mo-othman** [comment]
Hi we have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)

one of thew new features is you can add yaml and sync file(s)/folder(s)
