### ISSUE TITLE
AppImage version?

### ISSUE THREAD

**Issue by waldner** [guiqui/k8Studio#63]
Is an AppImage version of the application planned?

**Comment by mo-othman** [comment]
Hello @waldner , we will try to include it alongside the snap version in the upcoming release.

**Comment by waldner** [comment]
Thanks!

**Comment by mo-othman** [comment]
We have included AppImage version starting from v1.0.0-beta
https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta
