### ISSUE TITLE
Getting this error when I try to sign up. 

### ISSUE THREAD

**Issue by Simhan-dev** [guiqui/k8Studio#67]
---------
App Version 0.2.3-alpha
Arch: x64
Platform: darwin
osRelease: 22.6.0
Locale: en-GB
---------

**Comment by Simhan-dev** [comment]
![Screenshot 2024-01-25 at 12 14 19 PM](https://github.com/guiqui/k8Studio/assets/85724451/b461698e-6db5-4bb4-8a69-e71f845f2c66)

**Comment by mo-othman** [comment]
Hi @Simhan-dev It seems like It can't connect to the internet, Are you using a proxy?

**Comment by mo-othman** [comment]
Hi we have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)
Using proxy is supported now
