### ISSUE TITLE
Can not add a new cluster

### ISSUE THREAD

**Issue by Chainyinghao** [guiqui/k8Studio#68]
---------
App Version 0.2.3-alpha
Arch: x64
Platform: win32
osRelease: 10.0.23620
Locale: zh-CN
---------

![image](https://github.com/guiqui/k8Studio/assets/41147624/b48a74d5-3536-47ee-bfd1-ce00e0e9c458)

**Comment by Chainyinghao** [comment]
Do I need to install the kubectl tool?

**Comment by mo-othman** [comment]
Hi @Chainyinghao, 
Sorry we have missed this ticket

To address your previous question, yes, kubectl is indeed required for the proper functioning of the app.

If you have any more questions or feedback, please feel free to let us know. We're here to assist you
