### ISSUE TITLE
Cannot zoom out, only in, in, in...

### ISSUE THREAD

**Issue by amir-mehler** [guiqui/k8Studio#69]
I use my mouse scroll wheel to zoom in, counter direction won't zoom out.
Combining any alt/cmd/ctrl key won't help.
---------
App Version 0.2.3-alpha
Arch: arm64
Platform: darwin
osRelease: 23.2.0
Locale: en-US
---------

**Comment by mo-othman** [comment]
Hi we have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta), The issue should be fixed
