### ISSUE TITLE
"This account needs to be validated!"

### ISSUE THREAD

**Issue by zhenxuanxin** [guiqui/k8Studio#7]
Last month, the mail account was able to log in and use it normally, but when I tried to log in recently, I got the following prompt "This account needs to be validated!" at the top of the app.

version: `0.2.11` and `0.2.12`

screenshot:
![screenshot](https://user-images.githubusercontent.com/4496285/68914266-0a27e980-0799-11ea-9425-361057190ad2.png)

**Comment by gaogf** [comment]
me too

**Comment by guiqui** [comment]
I will recommend upgrading to version 2.13. Since the auth workflow has changed.
