### ISSUE TITLE
Cluster resources are upside down

### ISSUE THREAD

**Issue by amir-mehler** [guiqui/k8Studio#70]
<img width="1417" alt="image" src="https://github.com/guiqui/k8Studio/assets/6296994/707a90be-8417-4896-b201-a943f1416339">

---------
App Version 0.2.3-alpha
Arch: arm64
Platform: darwin
osRelease: 23.2.0
Locale: en-US
---------

**Comment by guiqui** [comment]
Thank you, Amir, looks like a transformation matrix with negative values.
I know what is the issue, is the wrong calculation of the viewport area, it will be fixed on the next release

**Comment by mo-othman** [comment]
Hi we have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta), The issue should be fixed
