### ISSUE TITLE
Invalid JSON error when trying to sign up

### ISSUE THREAD

**Issue by AnneauIntegre** [guiqui/k8Studio#72]
---------
App Version 0.2.3-alpha
Arch: x64
Platform: win32
osRelease: 10.0.19045
Locale: fr
---------

![image](https://github.com/guiqui/k8Studio/assets/104365812/3deccc67-7faa-4207-b222-dab3c30c375a)

Hello team, well that screenshot is pretty much it. I've just downloaded the app and when I try to sign up, I have this error.

**Comment by guiqui** [comment]
Looks like this happens, when using a proxy or SSO. We are changing the whole activation of the app this will be resolved in the next release.

**Comment by mo-othman** [comment]
Hi we have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)
Using proxy is supported now
