### ISSUE TITLE
Will this project support the ARM 64 architecture? 

### ISSUE THREAD

**Issue by baozitao** [guiqui/k8Studio#73]
ARM 64 architecture applications are increasing. We hope that the team can support ARM 64 architecture。

**Comment by guiqui** [comment]
Yes, we just need to add to our build script. I will put this one as a high priority.

**Comment by baozitao** [comment]
Thank you. This is an impressive project

**Comment by mo-othman** [comment]
Hi we have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta), Mac (ARM) is available 

Thanks!
