### ISSUE TITLE
my config is correct，but  can not login in,alway warming "Error Loading cluster can not load resources api"

### ISSUE THREAD

**Issue by beautifulxu** [guiqui/k8Studio#74]
---------
App Version 0.2.3-alpha
Arch: x64
Platform: win32
osRelease: 10.0.19045
Locale: zh-CN
---------
certificate-authority-data

**Comment by mo-othman** [comment]
Does the user you are using have access to API resources?
Can you run kubectl api-resources  on your terminal?

** I have removed the screenshot because of the data

**Comment by beautifulxu** [comment]
sure,It works fine when running through the command
![image](https://github.com/guiqui/k8Studio/assets/24916244/feaf7901-4c58-45e1-8c32-8b5f0d653a0e)

**Comment by mo-othman** [comment]
Just to confirm 
can you run  `kubectl api-resources`  command?

**Comment by mo-othman** [comment]
Hi we have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta), The issue should be fixed
