### ISSUE TITLE
Clicking on the Mac OS(Arm) button gives 404

### ISSUE THREAD

**Issue by andytael** [guiqui/k8Studio#77]
Trying to download Mac OS ARM install by clicking on the button gives 404 error.

**Comment by mo-othman** [comment]
Hi @andytael 
There's a typo in path, we are gonna update the website meanwhile you can download it from releases https://github.com/guiqui/k8Studio/releases

**Comment by mo-othman** [comment]
Hi we have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta)
