### ISSUE TITLE
No save button/any option To save New Cluster Details 

### ISSUE THREAD

**Issue by NMSVishal** [guiqui/k8Studio#78]
---------
App Version 0.2.3-alpha
Arch: x64
Platform: win32
osRelease: 10.0.22621
Locale: en-US
---------

**Comment by mo-othman** [comment]
Hi @NMSVishal we have released [v1.0.0-beta](https://github.com/guiqui/k8Studio/releases/tag/v1.0.0-beta), we have redesigned that part
