### ISSUE TITLE
Does not log into the pod containers. 

### ISSUE THREAD

**Issue by Simhan-dev** [guiqui/k8Studio#80]
---------
App Version 1.0.0-beta
Arch: x64
Platform: darwin
osRelease: 23.3.0
Locale: en-GB
---------

I am not able to get kubectl logs from the pods nor I am able to log into the containers. For container logs, when I click on the LOG icon, it  says "<master-ip>:6443" connection refused.

**Comment by mo-othman** [comment]
Hi @Simhan-dev, Can  know What are you getting when doing kubectl logs from your terminal?

**Comment by mo-othman** [comment]
Closed due to inactivity
