### ISSUE TITLE
Monitoring metrics don't work

### ISSUE THREAD

**Issue by advur** [guiqui/k8Studio#81]
On a bare-metal installation, the metrics are not working as expected. I have configured it with Prometheus Operator in Lens (prometheus-operator:9090 or kube-prometheus-stack:80), but the metrics are still not showing.

**Comment by advur** [comment]
Hello!
Of course, i use the full link that looks like monitoring/prometheus-operated:9090.
I'm attaching screenshots for clarity from my local minikube.

K8Studio
<img width="1242" alt="Screenshot 2024-04-18 at 15 12 48" src="https://github.com/guiqui/k8Studio/assets/92443043/8b0a32bd-316b-4aef-a776-b28f000dd5a2">

LENS
<img width="1486" alt="Screenshot 2024-04-18 at 15 16 35" src="https://github.com/guiqui/k8Studio/assets/92443043/a2331ec7-178f-4d93-a2e9-0e2694c355c3">
 
<img width="1242" alt="Screenshot 2024-04-18 at 15 12 48" src="https://github.com/guiqui/k8Studio/assets/92443043/775cc899-335a-440e-a435-5ddbefb1a13a">

**Comment by mo-othman** [comment]
Hi @advur Can i know what do you see under metrics tab in the item details view?

<img width="742" alt="Screenshot 2024-04-18 201410" src="https://github.com/guiqui/k8Studio/assets/42744048/a526600c-9f36-4555-a1cc-16eb4ffdae69">

**Comment by advur** [comment]
@mo-othman Hi! Indeed, there are CPU/RAM metrics in the pod tab

<img width="1760" alt="Screenshot 2024-04-18 at 16 18 23" src="https://github.com/guiqui/k8Studio/assets/92443043/7853714b-2063-4715-9836-dcf9d683748f">

**Comment by mo-othman** [comment]
do you have metrics server installed?
https://github.com/kubernetes-sigs/metrics-server

**Comment by advur** [comment]
No, it has not been installed. Now i've installed this and the metrics have started to be displayed. Is this targeted solution ?

**Comment by mo-othman** [comment]
Yes, To expose them through resource metrics api  (/metrics)
