### ISSUE TITLE
Waiting long time for graph to be ready when connecting to a large cluster

### ISSUE THREAD

**Issue by ErikLundJensen** [guiqui/k8Studio#85]
Displaying the "Deployment"-graph takes too long and contains too detailed/small to be useful.
Please. default to the "grid"-view instead of "Deployment"-view when connecting to a cluster.

**Comment by guiqui** [comment]
Hi Erik,
Can you give an idea of the size of your cluster, including the number of namespaces, workloads, pods, etc.?
I would like to set up a load test that mimics your configuration and reproduce the issue.

**Comment by ErikLundJensen** [comment]
for example 10 nodes, 50 namespaces, 500 pods
having 10 clusters in the hotbar if that has any effect.

**Comment by guiqui** [comment]
Thank you, the 10 clusters on the hotbar should not be part of the issue.
We have done load testing with 4000 pods and 40 namespaces with ok performance, we are setting a similar env to yours and see if the latest version has any issues.

**Comment by mo-othman** [comment]
Hi @ErikLundJensen we have released 1.0.9
Now you can configure the default view thorough the app settings

**Comment by ashokrajar** [comment]
@mo-othman I am currently on 2.x version. Where can I find this settings ? I am unable to locate.
