### ISSUE TITLE
Cant show Cronjobs

### ISSUE THREAD

**Issue by joli-sys** [guiqui/k8Studio#90]
---------
App Version 1.0.11-beta
Arch: arm64
Platform: darwin
osRelease: 23.3.0
Locale: en-GB 
ErrorMessage: selectedItem is not defined
---------

When I click on any cronJob `ErrorMessage: selectedItem is not defined` is showed up, and cluster view is closed.

**Comment by mo-othman** [comment]
Hi @joli-sys 
K8Studio-2.0.0 has been released and the issue should be fixed
