### ISSUE TITLE
Connection to private GKE cluster 

### ISSUE THREAD

**Issue by ognyan-lazarov-cloudoffice** [guiqui/k8Studio#91]
Fully private GKE cluster (Disabled External endpoints), added in K8Studio via Sync File(s). Connection to the cluster is carried out through IAP tunnel (tinyproxy).
After the tunnel is initiated successfully and there is an access to API server via kubectl
```
kubectl get no
NAME          STATUS     ROLES    AGE     VERSION
gke-...       Ready      <none>   7h59m   v1.29.5-gke.1091002
```
and K8Studio is started via the terminal, where the tunnel is active (analogically to Lens behaviour), double clicking on the cluster  inside the K8Studio UI ends up in timeout, showing the following popup:
![image](https://github.com/user-attachments/assets/972e3f4e-54ba-4dd4-af15-b409b09184b2)

When the proxy URL (http://localhost:8888) is added to Cluster Settings > Proxy tab, the result of connection initiation is expressed in this error notification:
![image](https://github.com/user-attachments/assets/8f0aad11-6c55-4af9-a779-0901cd14e14b)

And the status of the cluster is as follows:

![image](https://github.com/user-attachments/assets/42537662-f48f-4451-8cf1-ec86514abbe1)

The question is how it can be configured so that the connection is made successfully.

**Comment by guiqui** [comment]
Hi @ognyan-lazarov-cloudoffice thank you for reporting this bug, We are setting up a similar env.
One question can you change the proxy settings to HTTP://127.0.0.1:8888?

**Comment by ognyan-lazarov-cloudoffice** [comment]
> Hi @ognyan-lazarov-cloudoffice thank you for reporting this bug, We are setting up a similar env. One question can you change the proxy settings to [HTTP://127.0.0.1:8888](HTTP://127.0.0.1:8888)?

Hi, Guillermo!
Your quick reaction is highly appreciated!
It's working after the suggested solution - replacing localhost with 127.0.0.1
I should've thought of that. It's so simple and close to mind. My bad, sorry to troubles!
And a big thank you for your collaboration!

P.S. K8Studio is amazing, BTW!
Now you've got me over for good. I'm definitely migrating from Lens. :)

**Comment by guiqui** [comment]
THANK YOU, Your support means a lot to us, and we're excited to have you onboard
It should work with localhost too. We will correct it in the next release.

**Comment by ognyan-lazarov-cloudoffice** [comment]
Great!
I'm glad it'll be of value to all.

**Comment by mo-othman** [comment]
Fixed in v2
