### ISSUE TITLE
App not seeming to respect NO_PROXY

### ISSUE THREAD

**Issue by timgriffiths** [guiqui/k8Studio#92]
I can see it using the environment variables HTTP_PROXY and HTTPS_PROXY, but if I set these, I am not able to hit our internal clusters, which suggests to me it's not respecting the NO_PROXY environment variable

**Comment by guiqui** [comment]
Right, I going to take a look at the NO_PROXY logic to see why they are not getting excluded.

**Comment by guiqui** [comment]
We found the issue , the fix will be available in the next release.

**Comment by mo-othman** [comment]
Hi @timgriffiths 
K8Studio-2.0.0 has been released and the issue should be fixed
