### ISSUE TITLE
Unable to access log

### ISSUE THREAD

**Issue by ls-2018** [guiqui/k8Studio#95]
![image](https://github.com/user-attachments/assets/b0bf2ca1-b14b-4db7-a534-c92dcc6dfd70)

**Comment by ls-2018** [comment]
I found the reason, because I specified kubeconfig in the profile environment variable. I recommend using the -kubeconfig parameter to avoid this

**Comment by mo-othman** [comment]
Hi @ls-2018 Thanks for the update, we have noted it
